feat: Add commonly used unique id generators
Springworks/node-test-harness pull request #229
Opened 2016-10-05 15:13 UTC by nimerritt

2016-10-05 15:22 UTC, dbrockman requested changes

2016-10-05 15:22 UTC, dbrockman commented on test-data-helper.js
> +  return new ObjectId();
- [ ] This function can probably be removed

2016-10-05 15:22 UTC, dbrockman commented on test-data-helper.js
> +  return new ObjectId(object_id_string);
- [ ] remove this one as well

2016-10-05 15:22 UTC, dbrockman commented on test-data-helper.js
> +  return uniqueObjectId().toString();
```js
const crypto = require('crypto');

function uniqueObjectIdString() {
  return crypto.randomBytes(12).toString('hex');
}
```

2016-10-05 15:22 UTC, dbrockman commented on test-data-helper.js
> +  const id = new ObjectId();
- [ ] replace `new ObjectId()` with `uniqueObjectIdString()`

2016-10-05 15:25 UTC, dbrockman commented
- [ ] add a note in the readme about `require('@springworks/test-harness/test-data-helper')`

2016-10-05 15:38 UTC, dbrockman commented on test-data-helper.js
> +function randomRegNumber() {
Maybe we should rename this to `randomSwedishRegNumber`?

2016-10-06 06:24 UTC, nimerritt commented on test-data-helper.js
> +function randomRegNumber() {
I agree, but I want to minimise the refactoring of tests when using this package. Perhaps in the future, or with a argument with default value?

2016-10-06 11:15 UTC, dbrockman approved these changes

2016-10-06 11:17 UTC, merged